version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /WGSConcord/wdl/PfComputeDepthOfCoverage.wdl
    name: PfComputeDepthOfCoverage
    authors:
      - name: Brian Palmer
        email: bgpalmer14@gmail.com
    topic: Coverage

